version:              '2'
services:
  web_es:
    container_name:   es-digital-app-portal-dev
    image:            319701921293.dkr.ecr.eu-west-1.amazonaws.com/nginx:1.13.12-esure
    ports:            [ "8010:80" ]
    working_dir:      /usr/src/app1
    volumes:
      - .:/usr/src/app1
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./log:/var/log/nginx
      - ./docker/dist_es:/etc/nginx/html
    command:          [ "./docker/compose.sh" ]
    environment:
      - ACCESS_LOG_DIR=/tmp
      - XAPI_URL=http://localhost:4000
      - TAG_MANAGER_URL=//nexus.ensighten.com/ens-training36/dev/Bootstrap.js
      - OPTIMIZELY_URL=//cdn.optimizely.com/js/5369993155.js
      - SITE_CAT_ACCOUNT=esuredev
      - BRAND_URL=localhost:8010
      - LIVECHAT_URL=//cdn.synthetix.com/penfield/get_synthetix.min.js?applicationkey=3ea4141ea87348dbb912fb0da71ca70b&consumerkey=4c167aecf0453dea74659aadd46459df
      - IOVATION_URL=//ci-mpsnare.iovation.com/snare.js
      - RECAPTCHA_SITEKEY=6LdB7VYUAAAAAHX8Gh5MavUxxzRiWClu6UApHSfq
  web_sw:
      container_name: sw-digital-app-portal-dev
      image:          319701921293.dkr.ecr.eu-west-1.amazonaws.com/nginx:1.13.12-esure
      ports:          [ "8020:80" ]
      working_dir:    /usr/src/app1
      volumes:
        - .:/usr/src/app1
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./log:/var/log/nginx
        - ./docker/dist_sw:/etc/nginx/html
      command:        [ "./docker/compose.sh" ]
      environment:
        - ACCESS_LOG_DIR=/tmp
        - XAPI_URL=http://localhost:4000
        - TAG_MANAGER_URL=//nexus.ensighten.com/ens-training36/dev/Bootstrap.js
        - OPTIMIZELY_URL=//cdn.optimizely.com/js/5369993155.js
        - SITE_CAT_ACCOUNT=sheilaswheelsdev
        - BRAND_URL=localhost:8020
        - LIVECHAT_URL=//cdn.synthetix.com/penfield/get_synthetix.min.js?applicationkey=5195c62616d6e7db2d4ac1e860dfc995&consumerkey=4c167aecf0453dea74659aadd46459df
        - IOVATION_URL=//ci-mpsnare.iovation.com/snare.js
        - RECAPTCHA_SITEKEY=6LdB7VYUAAAAAHX8Gh5MavUxxzRiWClu6UApHSfq
  web_fa:
      container_name: fa-digital-app-portal-dev
      image:          319701921293.dkr.ecr.eu-west-1.amazonaws.com/nginx:1.13.12-esure
      ports:          [ "8030:80" ]
      working_dir:    /usr/src/app1
      volumes:
        - .:/usr/src/app1
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./log:/var/log/nginx
        - ./docker/dist_fa:/etc/nginx/html
      command:        [ "./docker/compose.sh" ]
      environment:
        - ACCESS_LOG_DIR=/tmp
        - XAPI_URL=http://localhost:4000
        - TAG_MANAGER_URL=//nexus.ensighten.com/ens-training36/dev/Bootstrap.js
        - OPTIMIZELY_URL=//cdn.optimizely.com/js/5369993155.js
        - SITE_CAT_ACCOUNT=firstalternativedev
        - BRAND_URL=localhost:8030
        - LIVECHAT_URL=//cdn.synthetix.com/penfield/get_synthetix.min.js?applicationkey=2ec1e480ed39a86a483affa164764f7a&consumerkey=4c167aecf0453dea74659aadd46459df
        - IOVATION_URL=//ci-mpsnare.iovation.com/snare.js
        - RECAPTCHA_SITEKEY=6LdB7VYUAAAAAHX8Gh5MavUxxzRiWClu6UApHSfq
